name: Build and Publish Website

on:
  push:
    paths:
      - R/**
      - DESCRIPTION
      - NEWS.md
      - .github/workflows/Pkgdown.yaml

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Cache R packages
        uses: actions/cache@v1
        if: runner.os != 'Windows'
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('DESCRIPTION') }}

      - name: Install Linux libraries
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev
          sudo apt-get install libcurl4-openssl-dev libv8-dev libjq-dev libprotobuf-dev protobuf-compiler libgit2-dev libharfbuzz-dev libfribidi-dev

      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck', 'devtools'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"

      - name: Install pkgdown
        run: |
          Rscript -e "install.packages(c('pkgdown'))"

      - name: Document Package
        run: |
          Rscript -e "devtools::document()"

      - name: Install package
        run: |
          Rscript -e "devtools::install()"

      - uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "current documentation update"

      - name: Build package website
        run: |
          Rscript -e "pkgdown::build_site()"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
