on:
  push:
    paths:
      - R/**
      - DESCRIPTION
      - .github/workflows/R-CMD-check.yaml
      - README.md
  schedule:
    - cron: "0 5 * * 1"

name: R-CMD-check

jobs:
  R-CMD-check:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Install Linux libraries
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev
          sudo apt-get install libprotobuf-dev protobuf-compiler libjq-dev
          sudo apt-get install pandoc

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('DESCRIPTION') }}

      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('remotes', 'rcmdcheck', 'devtools', 'rmarkdown'))"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"

      - name: Test
        run: Rscript -e "devtools::test()"

      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(args = c('--no-manual', '--no-tests', '--no-vignettes', '--no-build-vignettes'), build_args = c('--no-build-vignettes', '-no-manual'), error_on = 'error')"

      - uses: JasonEtco/create-an-issue@v2
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW: R-CMD-check
        with:
          filename: .github/workflow-fail-template.md
